# 1. Numpy Import

In [0]:
import numpy as np

###                   use 'as' to define an alias for abbreviaton

In [0]:
a = np.array([[1,2,3], [4,5,6]], dtype=np.float32)

In [0]:
print(a.ndim) #Print the array's dimension

2


In [0]:
print(a.shape) #Print the array's shape

(2, 3)


In [0]:
print(a.dtype) #Print the array's data type

float32


# 2&3. Array creation 


In [0]:
a = np.ones((3,5), dtype=np.float) # Create array with elements '1' float type

In [0]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
a = np.zeros((6,2), dtype=np.int8) # Create array with elements '0' int type

In [0]:
print(a)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [0]:
a = np.arange(1, 11) # Create linearly interpolated array

In [0]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [0]:
a = np.ones((2,3))
b = np.zeros((4, 3))
c = np.concatenate([a,b]) #Concatenate two NumPy arrays together

In [0]:
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
a = np.ones((4,1))
print(a)
b = np.zeros((4,2))
print (b)
c = np.concatenate([a,b], axis=1) #Concatenate two Numpy arrays in the second dimension

[[1.]
 [1.]
 [1.]
 [1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [0]:
print(c)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [0]:
#Covert data types
a = 17.5*np.ones((2,2))
print(a)

[[17.5 17.5]
 [17.5 17.5]]


In [0]:
print(a.astype(np.uint16)) #convert to unsigned int

[[17 17]
 [17 17]]


In [0]:
#Create arrays with the same shape
b = np.zeros_like(a)

In [0]:
print(b)

[[0. 0.]
 [0. 0.]]


In [0]:
print(b.shape)

(2, 2)


In [0]:
#Create random arrays
a = np.random.random((5,5))
print(a)

#Running multiple times you get different results

[[0.85868721 0.26334075 0.81630154 0.46266453 0.74094493]
 [0.77785267 0.81707388 0.8942205  0.20013708 0.05542101]
 [0.07041766 0.75173767 0.07944776 0.82724963 0.96379223]
 [0.37528614 0.83936681 0.35519995 0.40907278 0.98814115]
 [0.82534172 0.68249712 0.8130238  0.09241535 0.71970656]]


###  <span style="color: blue;">Arrays with different shapes cannot be added together</span> 

In [0]:
np.ones([7,8])+ np.zeros([2,4])

ValueError: operands could not be broadcast together with shapes (7,8) (2,4) 

# 4. Shaping in NumPy

In [0]:
a = np.array([1,2,3,4,5,6])

In [0]:
a = a.reshape(3,2)

In [0]:
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [0]:
a = a.reshape(2, -1)

In [0]:
print(a)

[[1 2 3]
 [4 5 6]]


In [0]:
a = a.ravel()

In [0]:
print(a)

[1 2 3 4 5 6]


### (1) In shaping, total number of elements cannot be changed
### (2) Use -1 to infer axis shape 
### (3) Row-major by default  <span style="color: red;">Matlab uses Column-major</span> 

# 5. Return values

### (1) Numpy functions return either views or copies.
### (2) Views share data with the original array, like references in Java/C++. Altering entries of a view, changes the same entries in the original.
### (3) Np.copy, np.view make explicit copies and views.


# 6. Transposition

In [0]:
a = np.arange(10).reshape(5, 2)
print(a)
b = np.arange(5,10)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[5 6 7 8 9]


In [0]:
a = a.T
print(a)

[5 6 7 8 9]


In [0]:
a = a.transpose((1,0)) # np.transpose the first two axes

In [0]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# 7. Saving and loading arrays

In [0]:
a = np.arange(10).reshape(5, 2)
print(a)
#save numpy array to files
np.savez('prssdata.npz', a=a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [0]:
#check current folder, the data.npz exists now

In [0]:
data = np.load('data.npz')
a = data['a']

In [0]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 1. npz files can hold multiple arrays
### 2. np.savez save compressed numpy array

# 8. Mathematical operators

### (1) Arithmatic operations are element-wise


In [0]:
a = np.arange(3)

In [0]:
print(a)

[0 1 2]


In [0]:
b = np.arange(4,7)

In [0]:
print(b)

[4 5 6]


In [0]:
a*b

array([ 0,  5, 12])

### (2) Logical operator return a bool array


In [0]:
a > 0.5

array([False,  True,  True])

### (3) In place operations modify the array

In [0]:
a += b
print(a)

[4 6 8]


# 9. Math, upcasting

Just as in Python and Java, the result of a math operator is cast to
to the more general or precise datatype:

uint64 + uint16 => uint64
float32/int32 => float32

 <span style="color: blue;">warning: upcasting does not prevent overflow</span> 

In [0]:
a = np.array(1);
print(a)
b = np.array(0);
print(b)

1
0


In [0]:
a/b  #returns  infinity

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


inf

# 10. Math universal functions

Also called ufuncs

Element-wise

Examples:

1.np.exp

2.np.sqrt

3.np.sin

4.np.cos

5.np.isnan

In [0]:
a = np.array([[1,4], [9, 16], [25, 36]])

In [0]:
np.sqrt(a)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [0]:
np.exp(a)

array([[2.71828183e+00, 5.45981500e+01],
       [8.10308393e+03, 8.88611052e+06],
       [7.20048993e+10, 4.31123155e+15]])

In [0]:
np.sin(a)

array([[ 0.84147098, -0.7568025 ],
       [ 0.41211849, -0.28790332],
       [-0.13235175, -0.99177885]])

In [0]:
np.cos(a)

array([[ 0.54030231, -0.65364362],
       [-0.91113026, -0.95765948],
       [ 0.99120281, -0.12796369]])

In [0]:
np.isnan(a)

array([[False, False],
       [False, False],
       [False, False]])

# 11. Indexing

In [0]:
x = np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [0]:
x[0,0] # top-left element

1

In [0]:
x[0, -1] # first row, last column

2

In [0]:
x[0, :] # first row (many entries)

array([1, 2])

In [0]:
x[:, 0] # first column (many entries)

array([1, 3])

### Notes:

Zero-indexing

Multi-dimensional indices are comma-separated (i.e., tuple)

# 12 . Indexing, slices, and arrays

In [0]:
x = np.array([[1,2], [3,4]])
x = x[1:, 1:] #select all but not the first row and column

In [5]:
print(x)

[]


In [0]:
x = np.array([[1,2], [3,4]])
x = x[:,::-1] # swap channel order
print(x)

[[2 1]
 [4 3]]


In [0]:
x = np.array([[1,2], [3,4]])
x[x<10] = 0 # set the elements smaller than 10 as 0
print(x)

[[0 0]
 [0 0]]


In [0]:
x = np.array([[1,2], [3,4]])
x = x[[1],:] # select the 2nd row
print(x)

[[3 4]]


### 1. Slices are views. Writing to a slice overwrites the original array
### 2. Can also index by a list or boolean array

# 13. Python Slicing

### Syntax: start:stop:step

In [15]:
a = list(range(10))
a[1:5]

[1, 2, 3, 4]

In [0]:
a[:3]

[0, 1, 2]

In [0]:
a[-3:]

[7, 8, 9]

In [0]:
a[3:8:2]

[3, 5, 7]

In [0]:
a[4:1:-1]

[4, 3, 2]

# 14. Axes

In [16]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [0]:
a.sum()

36

In [17]:
a.sum(axis=0) #sum over rows

array([ 6,  8, 10, 12])

In [18]:
a.sum(axis=1) #sum over columns

array([10, 26])

In [20]:
a.sum(axis=0, keepdims=True) #keep the dimension

array([[ 6,  8, 10, 12]])

### Use the axis parameter to control which dimension NumPy operates on
### Typically, the axis specified will disappear, keepdims keeps all dimensions

# 15. Broadcasting

In [0]:
a = np.array([1,2,3,4])
a = a + 1

In [22]:
print(a)

[2 3 4 5]


### When operating on multiple arrays, broadcasting rules are used.
### Each dimension must match, from right-to-left 
#### (1)Dimensions of size 1 will broadcast (as if the value was repeated). 
#### (2)Otherwise, the dimension must have the same shape. 
